const NepalDistrict: Record<string, Record<string, string>> = {
    "Koshi Province": {
        Taplejung: "Taplejung",
        Panchthar: "Panchthar",
        Ilam: "Ilam",
        Jhapa: "Jhapa",
        Morang: "Morang",
        Sunsari: "Sunsari",
        Dhankuta: "Dhankuta",
        Terhathum: "Terhathum",
        Sankhuwasabha: "Sankhuwasabha",
        Bhojpur: "Bhojpur",
        Solukhumbu: "Solukhumbu",
        Okhaldhunga: "Okhaldhunga",
        Khotang: "Khotang",
        Udayapur: "Udayapur",
    },
    "Madhesh Province": {
        Saptari: "Saptari",
        Siraha: "Siraha",
        Dhanusha: "Dhanusha",
        Mahottari: "Mahottari",
        Sarlahi: "Sarlahi",
        Rautahat: "Rautahat",
        Bara: "Bara",
        Parsa: "Parsa",
    },
    "Bagmati Province": {
        Dolakha: "Dolakha",
        Sindhupalchok: "Sindhupalchok",
        Rasuwa: "Rasuwa",
        Nuwakot: "Nuwakot",
        Dhading: "Dhading",
        Kathmandu: "Kathmandu",
        Bhaktapur: "Bhaktapur",
        Lalitpur: "Lalitpur",
        Kavrepalanchok: "Kavrepalanchok",
        Sindhuli: "Sindhuli",
        Ramechhap: "Ramechhap",
        Makwanpur: "Makwanpur",
        Chitwan: "Chitwan",
    },
    "Gandaki Province": {
        Gorkha: "Gorkha",
        Manang: "Manang",
        Mustang: "Mustang",
        Myagdi: "Myagdi",
        Kaski: "Kaski",
        Lamjung: "Lamjung",
        Tanahu: "Tanahu",
        Nawalpur: "Nawalpur",
        Syangja: "Syangja",
        Parbat: "Parbat",
        Baglung: "Baglung",
    },
    "Lumbini Province": {
        "Rukum East": "Rukum East",
        Rolpa: "Rolpa",
        Pyuthan: "Pyuthan",
        Gulmi: "Gulmi",
        Arghakhanchi: "Arghakhanchi",
        Palpa: "Palpa",
        "Nawalparasi East": "Nawalparasi East",
        Rupandehi: "Rupandehi",
        Kapilvastu: "Kapilvastu",
        Dang: "Dang",
        Banke: "Banke",
        Bardiya: "Bardiya",
    },
    "Karnali Province": {
        Dolpa: "Dolpa",
        Mugu: "Mugu",
        Humla: "Humla",
        Jumla: "Jumla",
        Kalikot: "Kalikot",
        Dailekh: "Dailekh",
        Jajarkot: "Jajarkot",
        "Rukum West": "Rukum West",
        Salyan: "Salyan",
        Surkhet: "Surkhet",
    },
    "Sudurpashchim Province": {
        Bajura: "Bajura",
        Bajhang: "Bajhang",
        Darchula: "Darchula",
        Baitadi: "Baitadi",
        Dadeldhura: "Dadeldhura",
        Doti: "Doti",
        Achham: "Achham",
        Kailali: "Kailali",
        Kanchanpur: "Kanchanpur",
    },
};

export default NepalDistrict;
